# Generated by Django 5.0.6 on 2024-06-02 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
